  swagger: '2.0'
  info:
    

    description: |
    
      stc, a leading digital telecommunication corporation, has developed the Connectivity Management Platform (CPM) APIs to assist organizations to manage and utilize their owned SIMs in a manner that provides them managed connectivity in multi-national, multi-level, and multi-operator environments.
      
      This specification is prepared for the API developers to assist them by managing their owned SIMs, to integrate their systems with the Connectivity Management Platform (CMP).
      
      # Release notes
      | Version |  Author |   Date      |  Notes   | 
      |--------|-------|-------|------------|
      | 2.1.0 | salim s toutah| 30 April 2021 | CR-47706 STC Network and IT Integrations <br> with Globetouch M2M Platform for General Motor <br> Initial Draft.
      | 2.1.1 | Muhammad Aamir Aftab| 2nd June 2021 | CR-47706 STC Network and IT Integrations <br> with Globetouch M2M Platform for General Motor <br> Added response body of cancelLocation in <br> POST /sims/{simId}/{identifier}/network/disconnected
      | 2.1.1 | Muhammad Aamir Aftab| 2nd June 2021 | CR-47706 STC Network and IT Integrations <br> with Globetouch M2M Platform for General Motor <br> Correct the spelling of 'operatorName' a response field of <br>Get Latest SIM Registration in <br> GET /sims/{simId}/{identifier}/registration.    
      | 2.1.1 | Muhammad Aamir Aftab| 2nd June 2021 | CR-47706 STC Network and IT Integrations <br> with Globetouch M2M Platform for General Motor <br> Added new resource Break Glass unders SIMS <br> PATCH /sims/{simId}/{identifier}/services/barring.
      | 2.2.0 | Muhammad Aamir Aftab| 17th August 2021 | Added a new resource to download the report. <br> **Reporting** => GET /reports/{reportId}.
      | 2.2.1 | Muhammad Aamir Aftab| 17th September 2021 | Added a new fields in the response. **SIM** => GET /sims.   
      | 2.2.1 | Muhammad Aamir Aftab| 18th September 2021 | Added the new entity named as **'apns'** in the <br> response of GET /sims/{simId}/{identifier}/diagnosis.
      | 2.2.1 | Muhammad Aamir Aftab| 19th September 2021 | Added the new field **'deliveryReceipt'** in the <br> request of POST /sms/sent. 
      | 2.2.1 | Muhammad Aamir Aftab| 22nd September 2021 | Added a missing fields, description and field maps of the response. **SIM** => GET /sims.         
      | 2.2.2 | Muhammad Aamir Aftab| 6th October 2021 | Added description and cardinality indicator in the field maps of the response. **SIM** => GET /sims.     
      | 2.3.0 | Muhammad Aamir Aftab| 10th October 2021 | Added a new resource to create the case of sims termination.<br> **SIM** => POST /sims/termination/case.   
      | 2.3.1 | Muhammad Aamir Aftab| 31st October 2021 | Added a new resource to terminate the sims.<br> **SIM** => DELETE /sims.       
      | 2.3.2 | Muhammad Aamir Aftab| 15 December 2021 | Update the enum from IN_PROGRESS to PROCEEDING of <br>GET /transactions/{transactionId}/status. 
    
    version: '2.3.1'

    contact:
      name: API Team
      email: api@stc.com.sa

  host: internal.api.stc.com.sa:4443
  basePath: enterprise/v1
  schemes:
    - http
  securityDefinitions:
    OAuth2ClientCredentials:
      description: Authorization using oAuth 2.0 Framework.
      type: oauth2
      tokenUrl: 'https://api.stc.com.sa/s-oidc/oAuth2/v1/token'
      flow: password
      scopes:
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/service.read': service profile read
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/servicestatus.read': service status read
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/bus.read': read business units
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/customer.read': read customer information
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/tc.read': read trigger counters
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/ccs.read': read cost centers
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/sessionsdisconnect.create': disconnect sessions
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/report.create': generate report
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/ccs.update': update cost centers
        'https://api.stc.com.sa/scope/euAuth/m2m/label/templatelabels.read': read template labels
        'https://api.stc.com.sa/scope/euAuth/m2m/label/templatelabels.create': create template labels
        'https://api.stc.com.sa/scope/euAuth/m2m/label/simaddto.create': add to SIM
        'https://api.stc.com.sa/scope/euAuth/m2m/label/simremove.update': remove from SIM
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/info.read': read sim info
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/usageAndCostInformation.read': read info
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/lastEvents.read': read last event
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/updateData.update': update data
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/changeServiceProfile.update': change service profile
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/moveToCostCenter.move': move cost center
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/moveToBusinessUnit.move': move BU
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/activate.action': activate sim
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/suspend.action': suspend sim
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/resume.action': resume sim
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/history.read': read sim history
        'https://api.stc.com.sa/scope/euAuth/m2m/sms/send': send sms
        'https://api.stc.com.sa/scope/euAuth/m2m/user/deactivate.action': deactivate user account 
        'https://api.stc.com.sa/scope/euAuth/m2m/user/users.read': get all users
        'https://api.stc.com.sa/scope/euAuth/m2m/user/users.update': update users
        'https://api.stc.com.sa/scope/euAuth/m2m/user/users.create': create users
        'https://api.stc.com.sa/scope/euAuth/m2m/user/credentials.create': create user credentials
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/networkdetails.read': read sim network detail
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/diagnosis.read': diagnosis sim information
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/voiceusage.read': read sim voice usage information
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/smsusage.read': read message usage information
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/datausage.read': read sim data usage information
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/status.read': read sims status information
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/modifiedsim.read': read modified sims information
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/networkdisconnect.create': disconnect sim from network
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/usageSummary.read': read sim usage summary      
        'https://api.stc.com.sa/scope/euAuth/m2m/ping': ping current api for healthcheck
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/device.update' : update sim's device infomration
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/registration.read' : read latest sim network registration
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/services/barring.update' : Update the  latest sim network registration   
        'https://api.stc.com.sa/scope/euAuth/m2m/utility/report.read' : Read report.    
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/terminate.case' : create the case of sims termination in platform.   
        'https://api.stc.com.sa/scope/euAuth/m2m/sims/delete' : Terminates the sims
        
  paths:
    /service/status:
      get:
        tags:
          - Service
        description: Is service available
        summary: Check if service is available
        operationId: isServiceAvailable
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/servicestatus.read'
    /service/profiles:
      get:
        tags:
          - Service
        description: Get all service profiles
        summary: Get all service profiles
        operationId: getAllServiceProfiles
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/service.read'
    /customer:
      get:
        tags:
          - Customer
        description: Get current customer information
        summary: Get Customer
        operationId: getMyCustomer
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/customer.read'
    /report:
      post:
        tags:
          - Reporting
        description: Generate report
        summary: Generate report
        operationId: generateReport
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/report.create'
    /reports/{reportId}:
      get:
        tags:
          - Reporting
        description: |
          This operation enables consumers to retrieve a report from Connectivity Management Platform (CMP) based on the specified report Id. 
          
          ## Supported File Types:-
          The supported file types of report are CSV, PDF and Excel.
          
          ## Response Headers 
          **1- Content-Type**
          The default content type is application/octet-stream. These octet-stream files are arbitrary binary data files that might be in .csv or .pdf or .xls format.


          **2- Content-Disposition**
          The Content-Disposition response header field conveys additional information about how to process the response payload. The Content-Disposition header field is defined as follows:
              "Content-Disposition" ":" disposition-type ";" disposition-param)
               ```Example Content-Disposition:attachment; filename = CDR Report 2021-08-16-Shaden.csv ```
         
          ***disposition-type***: The default value of disposition-type is being set as "attachment". Indicates that the user-agent should not display the response, but instead show a "Save As" dialog so that user can download the report as an attachement and save it locally.
          
          ***disposition-param - filename***:  The suggested filename for an eventual "Save As" dialog presented to the user. It could be used as a basis for the actual filename, where possible.
         
          ## Authorization Note:-
          This resource requires a valid OAuth2.0 access token for consumer who is not within stc network. Make sure you have the right scope for this API resource.
          
          
          ### OAuth Scope
          https://api.stc.com.sa/scope/euAuth/m2m/utility/report.read
          
          ## Flow
          ```
          +----------+                    +---------+                       +----------+
          | Consumer |                    |  APIM   |                       |   CMP    |
          +----------+                    +---------+                       +----------+
               |                                |                                 |     
               | 1- Download Report Request     |                                 |      
               |--------------------------->>   |                                 |  
               |                                | 2- Download Report Request      |  
               |                                | ----------------------------->> |  
               |                                |                                 |  
               |                                |  3- Download Report Reply       |  
               |                                | <<----------------------------- |  
               |                                |                                 |  
               |  4-  Download Report Reply     |                                 |  
               | <<---------------------------- |                                 |  
               |                                |                                 |    
          ```
          
          ## Examples
          #### Sample Request
          The following is a sample CURL request:
          ```
          curl -X GET \
            "https://${HOST}/m2m/v2/reports/{9989}"\
            -H "Authorization: Bearer tUAFR8WZYUltiQEW0iAkB7FyrwH3eHPCwGHg4zYjroQ6c4ycGvRp " \
            -H "X-STC-API-ClientMsgRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "X-STC-API-ClientCorrelationRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "Accept: application/json" \
         
          ```
          #### Sample Successful Response
          The following is a sample of a successful response in CSV Format:
          ```
            HTTP/1.1 200 OK 
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            Content-Type: application/Octet-Stream
            Content-Disposition:atachment; filename = CDR Report 2021-08-16-Shaden.csv
            Content-Length: 375
            IMSI;MSISDN;ICCID;CUSTNAME;BUNAME;CCNAME;SERVICEPROFILENAME;SESSION_STATE;DISPLAYABLESIMSTATUS;CUSTLABEL;BULABEL;CUSTOMERORDER_ID;REAL_USER_FINGERPRINT
          420011050983573;966830040793483;89966011050983573;بدالرب اناص;Shaden;;
          BUID_9286_GMConnected_Restricted_1;;0;ACTIVE;;;;VERIFIED
          420011050983573;966830040793483;89966011050983573;بدالرب اناص;Shaden;;
          BUID_9286_GMConnected_Restricted_1;;0;INACTIVE;;;;NOT_APPLICABLE          
          ```
          **Note:** The file extension of the report might be of .{csv/pdf/xls}.
          
          #### Sample Failure Response
          The following is a sample of a failure response:
          ```
            HTTP/1.1 400  
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            Content-Type: application/json
            {
              "httpStatusCode": 400,
              "error": {
                  "code": "API.400.InvalidReportId",
                  "message": "Generic Data Format validation error.",
                  "reason": "An invalid value was specified of 'reportId' path parameter.",
                  "moreInfoHref": "https://developers.stc.com.sa/docs/errors#API.400.1"
              }
            }

          ```        
          
          ## Payload Size Limit
           The payload size should be less than 500KB.

          
          ## Rate Limits: 10 Transaction Per Seconds (TPS).
          This API anticipates not more than 10 requests in a second.
          
          ## Error Codes 
          The following error codes may be returned
          | HTTP Status Code | &nbsp;&nbsp;&nbsp;&nbsp;Error Code| Error Reason |
          |----------------- |-----------|--------------|
          | 400 | API.400.InvalidReportId|An invalid value was specified of 'reportId' parameter.|  
       
          
        summary: Retrieve a report from Connectivity Management Platform (CMP). 
        operationId: getReport
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/utility/report.read
    /users:
      get:
        tags: 
          - Users
        description: Get information of users from the given domain id. Given domain may be customer identifier or business unit identifier.
        summary: Get information of users from the given domain id.
        operationId: getUsers
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/user/users.read'
      put:
        tags: 
          - Users
        description: Update users
        summary: Update user's information
        operationId: updateUsers
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/user/users.update'
      post:
        tags: 
          - Users
        description: Create user
        summary: Create new user
        operationId: createUser
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/user/users.create'
    /users/deactivated:
      put:
        tags: 
          - Users
        description: Deactivate users
        summary: Deactivate users
        operationId: deactivateUsers
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/user/deactivate.action'
    /users/{userid}/credentials:
      put:
        tags: 
          - Users
        description: Set user credentials
        summary: Set user credentials
        operationId: setUserCredentials
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/user/credentials.create'
    /labels/template:
      get:
        tags: 
          - Labels
        description: Get template labels
        summary: Get template labels
        operationId: getTemplateLabels
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/label/templatelabels.read
      post:
        tags: 
          - Labels
        description: Create template labels
        summary: Create template labels
        operationId: createTemplateLabels
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/label/templatelabels.create
    /sms/sent:
      post:
        tags: 
          - SMS
        description: |
          This operation enables consumers to send SMS messages either in a text or binary mode to a group of SIM cards at once.
          
          **Communication Style/ API Processing Pattern**:  Asynchronous Request-Response with Polling.
            Asynchronous operations create transactions in the M2M platform, and then return a transaction ID which can be used to query the status of the asynchronous operation by calling the **GET** ​/transactions​/{**transactionId**}​/status. The execution time of an asynchronous operation depends on the number of entities involved into the operation. 
            **Note:** The response header 'X-STC-API-TargetMsgRef' refers the transaction Id.
          
          # Request Fields 
            
          ## binary: a boolean flag 
          The value of this field is to be set as 'true' to send the binary message. The default value of this field is 'false' which implies that a message is to be sent in text mode.  
          
          ## deliveryReceipt: Delivery Receipt (DLR) - a boolean flag 
          A Delivery Receipt (DLR), also known as Delivery Report, is a special type of message which indicates the final state of a SMS. The value of this field is to be set as 'true' to receive delivery receipts for the SMSs that are delivered. The default value of this field is 'false' which implies that a Delivery Receipt is not requested by default for every SMS submission.            
          
          ## identifier: SIM Identifier 
          The SIM cards/identifier can be filtered by
          - ICCID
          - IMSI
          - MSISDN
          - Label
          
          **Note:**  If the identifier parameter is set to MSISDN, then it is possible for you, as a platform user, to send bulk SMSs to SIM cards that do not belong to the platform. While in case the identifier parameter is set to ICCID or IMSI, then the provided group of SIM cards, in the request, must belong to the platform.
          
          ## pin: PIN Verification Feature
          To send an SMS through this API operation, the PIN number, as stored in the SIM’s details, can be used as an additional security method to verify the allowed devices that can send SMS messages.
          
          This feature must first be enabled for your account. Once this is done, the bulk SMS will only be sent to the SIM cards whose PIN numbers match the PIN entries from the API call.For the SIM cards whose PIN numbers do not match the PIN entries, the message will not be delivered or charged, and an error message shall be returned.
          
          The PIN verification feature is neither enabled for SIM cards that are not included on the M2M Platform, nor enabled while using the platform GUI to perform the operation.
          
          ## Conditions
          
            &#9989;: true. &#10060; false,          
          |#|Use-case |Binary|Delivery Receipt|
          |-|----------- |-----------|-----------|
          |1|**Send Bulk SMS - Text Mode - Without Delivery Receipt**|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
          |2|**Send Bulk SMS - Text Mode - With Delivery Receipt**|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|  
          |3|**Send Bulk SMS - Binary Mode - Without Delivery Receipt**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|          
          |4|**Send Bulk SMS - Binary Mode - With Delivery Receipt**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|            

          
        summary:  send SMS in single or bulk
        operationId: bulkSMSSend
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sms/send'
    /businessunits:
      get:
        tags:
          - Business Unit
        description: Get business units by ids
        summary: Get business units by ids
        operationId: getBusinessUnitsByIds
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/bus.read'
    /costcenters:
      get:
        tags:
          - Cost Center
        description: Get cost centers by ids
        summary: Get cost centers by ids
        operationId: getCostCentersByIds
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/ccs.read'
      put:
        tags:
          - Cost Center
        description: Update cost centers
        summary: Update cost centers
        operationId: updateCostCenters
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/ccs.update'
    /sims:
      get:
        tags:
          - SIM
        description: |
       
           This operation enables consumers to get the SIMs information that is owned by the customer or by one of its business units by the specified identifiers. 
           
            ## Identifier
            Below are the possible identifiers.
            
              * ###  Offline & Online: search sims by online and offline
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A query parameter named 'information type' has two possible values **online** (Default) and **offline** to retrieve the offline and online SIM information. The below identifier is to be supplied along with this query parameter. 
             
         
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **ICCID**: search sims by ICCID for online and offline.
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **IMSI**: search sims by IMSI for online and offline..
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **MSISDN**: search sims by MSISDN (default) for online and offline.
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **LABEL**: search sims by sim Label ID for online and offline.
     
            - #### Examples
           
              ```
              Online (Default)
              ----------------
              CURL -X GET \"https://${HOST}/m2m/v2/sims?identifier=ICCID&ids=899660110050989126"\
                -H "Authorization: Bearer tUAFR8WZYUltiQEW0iAkB7FyrwH3eHPCwGHg4zYjroQ6c4ycGvRp " \
                -H "X-STC-API-ClientMsgRef: 8a969c6a-c28a-t546-gd79-961e6" \
                -H "X-STC-API-ClientCorrelationRef: 8a969c6a-c28a-t546-gd79-961e6" \
                -H "Accept: application/json" \ 
                
              Offline
              -------
              CURL -X GET \
                "https://${HOST}/m2m/v2/sims?identifier=ICCID&ids=899660110050989126&informationtype=offline"\
                -H "Authorization: Bearer tUAFR8WZYUltiQEW0iAkB7FyrwH3eHPCwGHg4zYjroQ6c4ycGvRp " \
                -H "X-STC-API-ClientMsgRef: 8a969c6a-c28a-t546-gd79-961e6" \
                -H "X-STC-API-ClientCorrelationRef: 8a969c6a-c28a-t546-gd79-961e6" \
                -H "Accept: application/json" \ 
              ```
               
            * ### CUSTOMER: search sims by customer-id
            * ###  BUSINESSUNIT: search sims by business unit id
            * ###  COSTCENTER: search sims by cost center id
 
             
            ## SIM Response -  Fields Map
            &#9989;: **Mandatory**, The specified field to be returned.
            &#9898;: **Optional**, The specified field may or may not be returned.  
            &#10060;: **Not Available**, The specified field will not be returned.
            |#|Field Name|Offline|Online|CUSTOMER|BUSINESS UNIT|COST CENTER
            |-|----------|--------|------|---------|-------------|------------|
            |1|**iccid**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|    
            |2|**imsi**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;| 
            |3|**msisdn**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|      
            |4|**businessUnitLabelsName**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|  
            |5|**customerLabelsName**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |6|**serviceProfileId**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;| 
            |7|**costCenterId**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|
            |8|**costCenterName**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;| 
            |9|**businessUnitId**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|  
            |10|**businessUnitName**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;| 
            |11|**resellerId**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|
            |12|**resellerName**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |13|**comment**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|  
            |14|**expectedIMEISV**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |15|**lastIMEIDetected**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |16|**cellID**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |17|**ipAddress**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|  
            |18|**lastIpAddressDetected**|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|  
            |19|**pinCode**|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|  
            |20|**sessionStateCode**|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |21|**sessionStartTime**|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |22|**simStateCode**|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|
            |23|**customerId**|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&#10060;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9989;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9898;|   
 

        operationId: getSIMsInfo
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/info.read'
      
      delete:
        tags:
          - SIM
        description: |
          This operation enables consumer to terminate the given SIM cards. You, as a platform user, can only terminate SIM cards that are owned by your customer or by one of its business units.
          
            **Communication Style/ API Processing Pattern**: Asynchronous.
            - **Pull the transaction status of an asynchronous operation.**
            Asynchronous operations create transactions in the M2M platform, and then return a transaction ID which can be used to query the status of the asynchronous operation by calling the **GET** ​/transactions​/{**transactionId**}​/status. The execution time of an asynchronous operation depends on the number of entities involved into the operation. 
            **Note:** The response header 'X-STC-API-TargetMsgRef' refers the transaction Id.
            
          ## Request Fields      
          
          ### Identifier:
            The SIMs can be filtered by one of the below identifiers.
            * ICCID
            * IMSI 
            * MSISDN
            * LABEL
            
          ### simIds[] Maximum Length:  
           This has a restriction of 500 SIM cards per request, at maximum, based on the SIM cards’ identifiers.    
          
          ## Authorization Note:-
          This resource requires a valid OAuth2.0 access token for consumer who is not within stc network. Make sure you have the right scope for this API resource.
          
          * OAuth Scope
          https://api.stc.com.sa/scope/euAuth/m2m/sims/delete
          
          ## Asynchronous Flow
          ```
          +----------+                      +---------+                         +----------+
          | Consumer |                      |  APIM   |                         |   CDP    |
          +----------+                      +---------+                         +----------+
               |                                  |                                   |     
               | 1-SIM(s) termination Request     |                                   |      
               |--------------------------->>     |                                   |  
               |                                  | 2- SIM(s) termination Request     |  
               |                                  | ----------------------------->>   |  
               |                                  |                                   |  
               |                                  |  3-SIM(s) termination Reply       |  
               |                                  | <<-----------------------------   |  
               |                                  |                                   |  
               |  4-SIM(s) termination Reply      |                                   |  
               | <<----------------------------   |                                   |  
               |                                  |                                   |   
               |           <<Time Lapsed>> Pull the transaction status                | 
               |              GET ​/transactions​/{transactionId}​/status.               |
               | <<----------------------------------------------------------->>      |  
               |                                  |                                   |     
               | 1-Get Transaction status Request |                                   |      
               |------------------------------->> |                                   |  
               |                                  | 2- Get Transaction status Request |  
               |                                  | ------------------------------->> |  
               |                                  |                                   |  
               |                                  | 3- Get Transaction status Reply   |  
               |                                  | <<-----------------------------   |  
               |                                  |                                   |  
               |  4-Get Transaction status Reply  |                                   |  
               | <<-----------------------------  |                                   |  
               |                                  |                                   |                  
          ```
          
          ## Examples
          #### Sample Request
          The following is a sample CURL request:
          ```
          curl -X DELETE \
            "https://${HOST}/m2m/v2/sims"\
            -H "Authorization: Bearer tUAFR8WZYUltiQEW0iAkB7FyrwH3eHPCwGHg4zYjroQ6c4ycGvRp " \
            -H "X-STC-API-ClientMsgRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "X-STC-API-ClientCorrelationRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "Accept: application/json" \
            -d '{
                  "identifier": "ICCID",
                  "simIds": [
                    "899660110050984521",
                    "899660110050983695",
                    "899660110050983696"
                  ]
               }'
          ```
          #### Sample Successful Response
          The following is a sample of a successful response:
          ```
            HTTP/1.1 202 Accepted 
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 370895
          ```
          
          #### Sample Failure Response
          The following is a sample of a failure response:
          ```
            HTTP/1.1 400  
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            Content-Type: application/json
            {
              "httpStatusCode": 400,
              "error": {
                  "code": "API.400.InvalidIdentifier",
                  "message": "Generic Data Format validation error.",
                  "reason": "An invalid value was specified of 'identifier' parameter.",
                  "moreInfoHref": "https://developers.stc.com.sa/docs/errors#API.400.1"
              }
            }

          ```        
          
          ## Rate Limits: 10 Transaction Per Seconds (TPS).
          This API anticipates not more than 10 requests in a second.
          
          ## Payload Size Limit
          The payload size should be less than 500KB.

          ## Error Codes 
          The following error codes may be returned
          | HTTP Status Code | &nbsp;&nbsp;&nbsp;&nbsp;Error Code| Error Reason |
          |----------------- |-----------|--------------|
          | 400 | API.400.MissingIdentifier| Missing mandatory parameter 'identifier'.           
          | 400 | API.400.InvalidIdentifier|An invalid value was specified of 'identifier' parameter.|
          | 400 | API.400.MissingSIMIds| Missing mandatory parameter 'simIds[]'.        
          | 400 | API.400.MissingSIMIdsElement| The simIds[] must contain at least one element.  
          | 400 | API.400.MaximumSIMLengthExceeded| The maximum length of simIds[] has been exceeded. 
          
        summary: Terminate given SIM cards.
        operationId: terminateSIMs
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/sims/delete
    /sims/modified:
      get:
        tags:
          - SIM
        description: 'Retrieve the modified SIMs based on the caller level; for example if the API caller is  OPCO user system should retrieve all the changed SIMs for all customers under the OPCO level and so on'
        summary: 'Retrieves Modified Sims.'
        operationId: getModifiedSims 
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/modifiedsim.read'
    /sims/{simId}/{identifier}: 
      patch:
        tags:
          - SIM
        summary: 'Update SIM data'
        description: 'The API used to update the IP address for the SIM and expected IMEI. In case the IP address has a value, IoT plateform system need provision that static IP for that SIM in HLR system so whenever the SIM initiate a new data session, it will be automatically assigned with that static IP address. The list of SIMs can be all updated successfully or partially success meaning update action done successfully for some SIMs and failed for the rest.'
        operationId: updateSIMData
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/updateData.update'              
    /sims/{simId}/{identifier}/session/disconnected:
      post:
        tags:
          - SIM
        description: 'The API used to disconnect a data session for list of given SIM cards. The list of SIMs can be all disconnected successfully or partially success meaning disconnect action done successfully for some SIMs and failed for the rest.'
        summary: 'Disconnect SIM Data Sessions'
        operationId: disconnectSessions
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/sessionsdisconnect.create'
    /sims/{simId}/{identifier}/network/disconnected:
      post:
        tags:
          - SIM
        description: 'This API will clear the subscriber data from previous MS/VLR and disconnects it from network, after this the device will reconnects to network itself. This API will be Asynchronous request and will return the Transaction ID, status of which can be queried through existing API getRequestStatus. Below are the request and response parameters for this API.'
        operationId: cancelLocation
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/networkdisconnect.create'
    /sims/{simId}/{identifier}/network: 
      get:
        tags:
          - SIM
        description: 'Retrieve information about network details associated with the last data session for given SIM, which must be owned by the customer (or one of its business units) who is invoking the service.' 
        summary: 'Retrieve access network details'
        operationId: getSIMAccessNetworkDetails 
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/networkdetails.read'  
    /sims/{simId}/{identifier}/diagnosis: 
      get:
        tags:
          - SIM
        description: 'Performs the diagnosis of one SIM. SIM to be diagnosed must be owned by the customer (or one of its business units) who is invoking the service' 
        summary: 'Retrieve diagnosis of one SIM'
        operationId: DiagnoseSIM  
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/diagnosis.read'
    /sims/label:
      post:
        tags: 
          - SIM
        description: Add label to SIM
        summary: Add label to SIM
        operationId: addLabelToSIM
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/label/simaddto.create'
      delete:
        tags: 
          - SIM
        description: Remove label from SIM
        summary: Remove label from SIM
        operationId: removeLabelFromSIM
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/label/simremove.update'
    /sims/{simId}/{identifier}/usage/summary:
      get:
        tags:
          - SIM
        description: This API will return the usage summary from the last bill date till the API call date. For new SIMs, the usage summary has to be prepared from the SIM activation date till the API call date. 
        summary: Get SIM usage summary
        operationId: getSIMsUsageSummary
        security:
          - OAuth2:
              - >-
                https://api.stc.com.sa/scope/euAuth/m2m/utility/usageSummary.read
    /sims/usage:
      get:
        tags:
          - SIM
        description: Get SIM usage and cost details
        summary: Get SIM usage and cost details
        operationId: getSIMsUsageAndCostDetails
        security:
          - OAuth2:
              - >-
                https://api.stc.com.sa/scope/euAuth/m2m/sims/usageAndCostInformation.read
    /sims/voice/usage: 
      get:
        tags:
          - SIM
        description: 'Provide the voice usage for given sims list using a sim identifier during a current bill cycle, SIM must be owned by the customer (or one of its business units) who is invoking the service'
        summary: 'Provide the voice usage'
        operationId:  GetSIMsVoiceCurentCycleLastUsageDetails   
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/voiceusage.read'              
    /sims/sms/usage: 
      get:
        tags:
          - SIM
        description: 'Provide the sms usage for given sims list using a sim identifier during a current bill cycle, SIM must be owned by the customer (or one of its business units) who is invoking the service.'
        summary: 'Provide the sms usage'
        operationId: GetSIMsSMSCurrentCycleUsageDetails    
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/smsusage.read'
    /sims/data/usage: 
      get:
        tags:
          - SIM
        description: 'Provide the data usage for given sims list using a sim identifier during a current bill cycle, SIM must be owned by the customer (or one of its business units) who is invoking the service.'
        summary: 'Provide the data usage'
        operationId: GetSIMsCurrentCycleDataUsageDetails     
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/datausage.read'
    /sims/history:
      get:
        tags:
          - SIM
        description: Get SIM history
        summary: Get SIM history
        operationId: getSIMHistory
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/history.read'
    /sims/lastevents:
      get:
        tags:
          - SIM
        description: 'Retrieve the last 15 usage events details for a given sims list using a sim identifier. SIM must be owned by the customer (or one of its business units) who is invoking the service.'
        summary: 'Retrieve the last SIM usage events '
        operationId: getSIMLastEvents
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/lastEvents.read'
    /sims/serviceprofile:
      put:
        tags:
          - SIM
        description: 'Change the service profile of the given SIM cards. SIMs to be moved must be owned by the customer (or one of its business units/cost center) who is invoking the service. The target service profile must have the option “Allow manual transition”.The SIMs can be searched by ICCID, IMSI, MSISDN or LABEL.Note: The number of allowed change service profile is limited. When a change SIMs service profile call is executed with some SIMs who reached this limit, they are ignored in the[...]'
        summary: 'Change SIM service profile'
        operationId: changeSIMsServiceProfile
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/sims/changeServiceProfile.update
    /sims/costcenter/move:
      post:
        tags:
          - SIM
        description: Move SIMs to cost center
        summary: Move SIMs to cost center
        operationId: moveSIMsToCostCenter
        security:
          - OAuth2:
              - >-
                https://api.stc.com.sa/scope/euAuth/m2m/sims/moveToCostCenter.move
    /sims/businessunit/move:
      post:
        tags:
          - SIM
        description: 'SIMs to be moved must be owned by the customer (or one of its business units) who is invoking the service'
        summary: 'Move SIMs to Business unit'
        operationId: moveSIMsToBusinessUnit
        security:
          - OAuth2:
              - >-
                https://api.stc.com.sa/scope/euAuth/m2m/sims/moveToBusinessUnit.move
    /sims/{simId}/{identifier}/triggercounter/{triggerId}:
      get:
        tags:
          - SIM
        description: "API call returns: data (in bytes) or SMS, which has been consumed by the SIM up to the API call (which is measured by a counter), limit set on trigger and remaining amount of data(in bytes) or SMS. The trigger counter is reset in case of a Service Profile change, or is set to zero again when a data volume trigger has fired been fired."
        summary: "retrieves the trigger counters"
        operationId: getTriggerCounters
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/tc.read'
    /sims/{simId}/{identifier}/triggerdetails:
      get:
        tags:
          - SIM
        description: "This API retrieves the triggers details configured on a given SIM card using SIM identifier."
        summary: "Retrieves the triggers details"
        operationId: gettriggersdetail 
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/utility/tc.read'
    /sims/activated:
      post:
        tags:
          - SIM
        description: Activate SIMs
        summary: Activate SIMs
        operationId: activateSIMs
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/activate.action'
    /sims/suspended:
      post:
        tags:
          - SIM
        description: Suspend SIMs
        summary: Suspend SIMs
        operationId: suspendSIMs
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/suspend.action'
    /sims/resumed:
      post:
        tags:
          - SIM
        description: Resume SIMs
        summary: Resume SIMs
        operationId: resumeSIMs
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/resume.action'
              
    /sims/{simId}/{identifier}/device:
      patch:
        tags:
          - Device
        description: This API is to initiate update of device identification and should store against the subscription in M2M platform. 
        summary: 'Update Device Id associatd with SIM'
        operationId: updateDevice 
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/device.update'
    /sims/{simId}/{identifier}/registration:
      get:
        tags:
          - SIM
        description: This API is called order to fetch latest SIM registration timestamp on the network along with network element address. It will output Network Registration Status, Last Registration Timestamp, Network Element Name and Network Element Address. 
        summary: Get Latest SIM Network Registration Details
        operationId: getRegistrationDetails
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/utility/registration.read
    /sims/{simId}/{identifier}/services/barring:
      patch:
        tags:
          - SIM
        description: |
          This operation enables consumer to suspend/bar and resume/unbar voice, incoming voice, outgoing voice, data, and SMS services independently or simultaneously.
          
          ## Authorization Note:-
          This resource requires a valid OAuth2.0 access token for consumer who is not within stc network. Make sure you have the right scope for this API resource.
          
          ### OAuth Scope
          https://api.stc.com.sa/scope/euAuth/m2m/sims/services/barring.update
          
          ## Flow
          ```
          +----------+                    +---------+                       +----------+
          | Consumer |                    |  APIM   |                       |   IBOA   |
          +----------+                    +---------+                       +----------+
               |                                |                                 |     
               | 1-BAR/UNBAR Service(s) Request |                                 |      
               |--------------------------->>   |                                 |  
               |                                | 2- BAR/UNBAR Service(s) Request |  
               |                                | ----------------------------->> |  
               |                                |                                 |  
               |                                |  3-BAR/UNBAR Service(s) Reply   |  
               |                                | <<----------------------------- |  
               |                                |                                 |  
               |  4-BAR/UNBAR Service(s) Reply  |                                 |  
               | <<---------------------------- |                                 |  
               |                                |                                 |    
          ```
          
          ## Examples
          #### Sample Request
          The following is a sample CURL request:
          ```
          curl -X PATCH \
            "https://${HOST}/m2m/v2/sims/420011050985626>/IMSI/services/barring"\
            -H "Authorization: Bearer tUAFR8WZYUltiQEW0iAkB7FyrwH3eHPCwGHg4zYjroQ6c4ycGvRp " \
            -H "X-STC-API-ClientMsgRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "X-STC-API-ClientCorrelationRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "Accept: application/json" \
            -d '{
                  "services": [
                    {
                      "serviceSpecification": "Voice",
                      "operation": "UNBAR"
                    },
                    {
                      "serviceSpecification": "VoiceIncoming",
                      "operation": "UNBAR"
                    },
                    {
                      "serviceSpecification": "VoiceOutgoing",
                      "operation": "BAR"
                    },
                    {
                      "serviceSpecification": "Data",
                      "operation": "BAR"
                    },
                    {
                      "serviceSpecification": "SMS",
                      "operation": "UNBAR"
                    }
                  ]
                }'

          ```
          #### Sample Successful Response
          The following is a sample of a successful response:
          ```
            HTTP/1.1 200 OK 
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            Content-Type: application/json
            {
              "IMSI": "420011001113147",
              "MSISDN": "966830000000013",
              "services": [
                {
                  "serviceSpecification": "Voice",
                  "operation": "UNBAR",
                  "status": "SUCCESS"
                },
                {
                  "serviceSpecification": "VoiceIncoming",
                  "operation": "UNBAR",
                  "status": "SUCCESS"
                },
                {
                  "serviceSpecification": "VoiceOutgoing",
                  "operation": "BAR",
                  "status": "FAIL"
                },
                {
                  "serviceSpecification": "Data",
                  "operation": "BAR",
                  "status": "FAIL"
                },
                {
                  "serviceSpecification": "SMS",
                  "operation": "UNBAR",
                  "status": "SUCCESS"
                }
              ]
            }
          ```
          
          #### Sample Failure Response
          The following is a sample of a failure response:
          ```
            HTTP/1.1 400  
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            Content-Type: application/json
            {
              "httpStatusCode": 400,
              "error": {
                  "code": "API.400.InvalidIdentifier",
                  "message": "Generic Data Format validation error.",
                  "reason": "An invalid value was specified of 'identifier' path parameter.",
                  "moreInfoHref": "https://developers.stc.com.sa/docs/errors#API.400.1"
              }
            }

          ```        
          
          ## Rate Limits: 10 Transaction Per Seconds (TPS).
          This API anticipates not more than 10 requests in a second.
          
          ## Payload Size Limit
          The payload size should be less than 500KB.

          ## Error Codes 
          The following error codes may be returned
          | HTTP Status Code | &nbsp;&nbsp;&nbsp;&nbsp;Error Code| Error Reason |
          |----------------- |-----------|--------------|
          | 400 | API.400.InvalidIdentifier|An invalid value was specified of 'identifier' parameter.|  
          | 400 | API.400.MissingService| Missing mandatory parameter 'services'.   
          | 400 | API.400.MissingServiceElement| The services must contain at least one element.  
          | 400 | API.400.MissingServiceSpecification| Missing mandatory parameter 'serviceSpecification' 
          | 400 | API.400.MissingOperation| Missing mandatory parameter 'operation'       
          | 400 | API.400.InvalidServiceSpecification |An invalid value was specified of 'serviceSpecification' field.|  
          | 400 | API.400.InvalidOperation |An invalid value was specified of 'operation' field.|  

          
        summary: Break Glass BAR/Suspend Or UNBAR/Resume service(s)
        operationId: breakGlass
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/sims/services/barring.update
    /sims/termination/case:
      post:
        tags:
          - SIM
        description: |
          This operation enables consumer to create sims termination case of given SIM cards. You, as a platform user, can only terminate the SIM cards that are owned by your customer or by one of its business units. 
            Kindly note that sims will not be terminated promptly but the request will go through the **'Termination and Retention'** process before it got handled. The platform will initially suspend the given sim cards, create a case of sims termination and assign it to **Retention Team**. The retention team will attempt to negotiate with the customer. If a customer accepts the retention offer the given sim cards are to be resumed. In case of rejection of retention offer the given sims cards t[...] 
          
            **Communication Style/ API Processing Pattern**: Asynchronous.
            - **Pull the transaction status of an asynchronous operation.**
            Asynchronous operations create transactions in the M2M platform, and then return a transaction ID which can be used to query the status of the asynchronous operation by calling the **GET** ​/transactions​/{**transactionId**}​/status. The execution time of an asynchronous operation depends on the number of entities involved into the operation. 
            **Note:** The response header 'X-STC-API-TargetMsgRef' refers the transaction Id.
            
          ## Request Fields      
          
          ### Identifier:
            The SIMs can be filtered by one of the below identifiers.
            * ICCID
            * IMSI 
            * MSISDN
            * LABEL
            
          ### simIds[] Maximum Length:  
           This has a restriction of 500 SIM cards per request, at maximum, based on the SIM cards’ identifiers.    
          
          ## Authorization Note:-
          This resource requires a valid OAuth2.0 access token for consumer who is not within stc network. Make sure you have the right scope for this API resource.
          
          * OAuth Scope
          https://api.stc.com.sa/scope/euAuth/m2m/sims/terminate.case
          
          ## Asynchronous Flow
          ```
          +----------+                      +---------+                         +----------+
          | Consumer |                      |  APIM   |                         |   CDP    |
          +----------+                      +---------+                         +----------+
               |                                  |                                   |     
               | 1-SIM termination Case Request   |                                   |      
               |--------------------------->>     |                                   |  
               |                                  | 2- SIM termination Case Request   |
               |                                  | ----------------------------->>   |  
               |                                  |                                   |  
               |                                  |  3-SIM termination Case Reply     |  
               |                                  | <<-----------------------------   |  
               |                                  |                                   |  
               |  4-SIM termination Case Reply    |                                   |  
               | <<----------------------------   |                                   |  
               |                                  |                                   |   
               |           <<Time Lapsed>> Pull the transaction status                | 
               |              GET ​/transactions​/{transactionId}​/status.            |
               | <<----------------------------------------------------------->>      |  
               |                                  |                                   |     
               | 1-Get Transaction status Request |                                   |      
               |------------------------------->> |                                   |  
               |                                  | 2- Get Transaction status Request |  
               |                                  | ------------------------------->> |  
               |                                  |                                   |  
               |                                  | 3- Get Transaction status Reply   |  
               |                                  | <<-----------------------------   |  
               |                                  |                                   |  
               |  4-Get Transaction status Reply  |                                   |  
               | <<-----------------------------  |                                   |  
               |                                  |                                   |                  
          ```
          
          ## Examples
          #### Sample Request
          The following is a sample CURL request:
          ```
          curl -X POST \
            "https://${HOST}/m2m/v2/sims/termination/case"\
            -H "Authorization: Bearer tUAFR8WZYUltiQEW0iAkB7FyrwH3eHPCwGHg4zYjroQ6c4ycGvRp " \
            -H "X-STC-API-ClientMsgRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "X-STC-API-ClientCorrelationRef: 8a969c6a-c28a-t546-gd79-961e6" \
            -H "Accept: application/json" \
            -d '{
                  "identifier": "ICCID",
                  "simIds": [
                    "899660110050984521",
                    "899660110050983695",
                    "899660110050983696"
                  ]
               }'
          ```
          #### Sample Successful Response
          The following is a sample of a successful response:
          ```
            HTTP/1.1 202 Accepted 
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 370895
          ```
          
          #### Sample Failure Response
          The following is a sample of a failure response:
          ```
            HTTP/1.1 400  
            Content-Type: application/json;charset=UTF-8,
            X-STC-API-ApiMsgRef: 92ff21d4-25ef-4df6-ab24-4f0b2ded1c9c,
            X-STC-API-ClientCorrelationRef: "8a969c6a-c28a-t546-gd79-961e6,
            X-STC-API-ClientMsgRef: 4f0b2ded1c9c-c28a-t546-gd79-961e6,
            Content-Type: application/json
            {
              "httpStatusCode": 400,
              "error": {
                  "code": "API.400.InvalidIdentifier",
                  "message": "Generic Data Format validation error.",
                  "reason": "An invalid value was specified of 'identifier' parameter.",
                  "moreInfoHref": "https://developers.stc.com.sa/docs/errors#API.400.1"
              }
            }

          ```        
          
          ## Rate Limits: 10 Transaction Per Seconds (TPS).
          This API anticipates not more than 10 requests in a second.
          
          ## Payload Size Limit
          The payload size should be less than 500KB.

          ## Error Codes 
          The following error codes may be returned
          | HTTP Status Code | &nbsp;&nbsp;&nbsp;&nbsp;Error Code| Error Reason |
          |----------------- |-----------|--------------|
          | 400 | API.400.MissingIdentifier| Missing mandatory parameter 'identifier'.           
          | 400 | API.400.InvalidIdentifier|An invalid value was specified of 'identifier' parameter.|
          | 400 | API.400.MissingSIMIds| Missing mandatory parameter 'simIds[]'.        
          | 400 | API.400.MissingSIMIdsElement| The simIds[] must contain at least one element.  
          | 400 | API.400.MaximumSIMLengthExceeded| The maximum length of simIds[] has been exceeded. 
          
        summary: Create a sims termination case of given SIM cards in platform.
        operationId: createSIMTerminationCase
        security:
          - OAuth2:
              - https://api.stc.com.sa/scope/euAuth/m2m/sims/terminate.case
    /transactions/{transactionId}/status:
      get:
        tags:
          - Transaction
        description: Inquire M2M Platform about the status of their created asynchronous requests.
        summary: 'Get Request Status'
        operationId: getRequestStatus 
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/sims/status.read'
    /monitoring/ping:
      get:
        tags:
          - Ping
        description: Ping API.
        summary: Healthcheck ping API for.
        operationId: echo 
        security:
          - OAuth2:
              - 'https://api.stc.com.sa/scope/euAuth/m2m/ping'             